### ISSUE TITLE
Table Driven Tests & Mocks for Models

### ISSUE THREAD

**Issue by mrcrilly** [mrcrilly/superwishlists#2]
- Implement TDTs using `gotests` 
- Implement mock structures for components that require it (possibly none.)

## TODO
- [ ] `gotests` generation comments
- [ ] Write table tests for each unit to implement business logic

## Perhaps
- [ ] `moq` generation comments (where appropriate; don't mock every interface)
